/*
The system must ask the user for an integer between 0 and 10.
The system must generate a random number between 0 and 10.
If the user's number is greater than the system's generated number, then the user wins.
Otherwise, the system wins.

The system must inform the user who won.
The system must display an error message if the user's input is not in the desired range.
The system must display an error message if the user's input is not a number.

Let the user choose game "level" - tell the user what each level means:
    Easy: program will tell you if it was higher or equal (you win) or lower (computer wins) than the program's number.
    Medium: program will tell you if it was strictly higher (you win) or lower or equal (computer wins) than the program's number.
    Hard: program will tell you if it was equal (you win) or not (you lose) to the program's number.

Store each game level “explanation message” in an array and use the level indicated by the user to index into the array.
*/

import java.util.Scanner;
import java.util.Random;

public class Main {

    // instance variables
    static int systemRandomNumber;
    static int userRandomNumber;
    static Scanner reader;

    // main method
    public static void main(String[] args) {
        try {
            reader = new Scanner(System.in);
            chooseMode();
            reader.close();
        }  catch (Exception e) {
            System.err.println("you messed up");
        }
    }

    // Main driver method
    public static void chooseMode() {

        // prints out the description of difficulty levels and their respective description
        String[] difficulty = {
            "1. Easy Difficulty: program will tell you if it was higher or equal (you win) or lower (computer wins) than the program's number.", 
            "2. Medium Difficulty: program will tell you if it was strictly higher (you win) or lower or equal (computer wins) than the program's number.", 
            "3. Hard Difficulty: program will tell you if it was equal (you win) or not (you lose) to the program's number."
        };
        System.out.println("Choose a difficulty by entering a valid number (1,2 or 3):");
        for (String s : difficulty)
            System.out.println(s);

        // lets user select which difficult mode in which an user wants to play
        try {
            if (reader.hasNextInt()) {
                int level = reader.nextInt();
                if (level == 1) {
                    easyMode();
                } else if (level == 2) {
                    mediumMode();
                } else if (level == 3) {
                    hardMode();
                } else {
                    System.err.println("ERROR: Enter the valid difficulty level.");
                    System.exit(1);
                }
            } else {
                System.err.println("ERROR: Enter the valid value.");
                System.exit(1);
            }
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }

    }

    // 1. Easy: program will tell you if it was higher or equal (you win) or lower (computer wins) than the program's number.
    public static void easyMode() {

        System.out.println("========== You are playing an easy mode ==========");
        getSystemInput();
        getUserInput();

        if (systemRandomNumber > userRandomNumber) {
            System.out.println("System generated " + systemRandomNumber + " and you entered " + userRandomNumber + ".");
            System.out.println("Since the system has the higher number than your number, SYSTEM WON this time.");
        } else {
            System.out.println("System generated " + systemRandomNumber + " and you entered " + userRandomNumber + ".");
            System.out.println("Since you have the number that is higher than or equal to number generated by the system, YOU WON this time.");
        }

    }

    // 2. Medium: program will tell you if it was strictly higher (you win) or lower than or equal to (computer wins) the program's number.
    public static void mediumMode() {

        System.out.println("========== You are playing a medium mode ==========");
        getSystemInput();
        getUserInput(); 

        if (systemRandomNumber >= userRandomNumber) {
            System.out.println("System generated " + systemRandomNumber + " and you entered " + userRandomNumber + ".");
            System.out.println("Since the system has the number that is higher than or equal to your number, SYSTEM WON this time.");
        } else {
            System.out.println("System generated " + systemRandomNumber + " and you entered " + userRandomNumber + ".");
            System.out.println("Since you have the number that is strictly higher than the number generated by the system, YOU WON this time.");
        }
    }

    // 3. Hard: program will tell you if it was equal (you win) or not (you lose) to the program's number.
    public static void hardMode() {

        System.out.println("========== You are playing a hard mode ==========");
        getSystemInput();
        getUserInput();

        if (systemRandomNumber == userRandomNumber) {
            System.out.println("System generated " + systemRandomNumber + " and you entered " + userRandomNumber + ".");
            System.out.println("The system has the same number than your number, YOU WON this time.");
        } else {
            System.out.println("System generated " + systemRandomNumber + " and you entered " + userRandomNumber + ".");
            System.out.println("You have the number that is different than the number generated by the system, SYSTEM WON this time.");
        }
    }

    // helper method: get input from the system
    public static void getSystemInput() {

        try {

            System.out.println("Please enter a lower bound for the number that the system can generate: ");

            if (!reader.hasNextInt()) {
                System.err.println("ERROR: You did not enter the integer value. Please try again.");
                System.exit(1);
            }
            int lowerBoundNum = reader.nextInt();   

            System.out.println("Now please define a upper bound: ");

            if (!reader.hasNextInt()) {
                System.err.println("ERROR: You did not enter the integer value. Please try again.");
                System.exit(1);
            }
    
            int upperBoundNum = reader.nextInt();

            systemRandomNumber = generateRandomNumber(lowerBoundNum, upperBoundNum);
            System.out.println("================");
            System.out.println("System has generated the random number between " + lowerBoundNum + " and " + upperBoundNum);
            System.out.println("================");

        } catch (Exception e) {
            System.err.println("ERROR: Something went wrong. Please try again.");
        }

    }

    // helper method: get input from an user
    public static void getUserInput() {

        try {
            System.out.println("Now it is your turn to generate the number between defined ranges");
            if (!reader.hasNextInt()) {
                System.err.println("ERROR: You did not enter the integer value. Please try again.");
                System.exit(1);
            }
            userRandomNumber = reader.nextInt();

        } catch (Exception e) {
            System.err.println("ERROR: Something went wrong. Please try again.");
        }

    }

    // helper method: return a system-generated random number
    public static int generateRandomNumber(int i, int j) {

        try {
            Random rand = new Random();
            if (j >= i) {
                int n = rand.nextInt(j+1-i) + i;
                return n;
            } else {
                System.err.println("It seems like upper bound is lower than the lower bound. Please try again.");
                System.exit(1);
            }
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
        return -1;
        
    }

}